"""
build_index.py — Groove Hub Wiki Index Generator
Scans all .md nodes in wiki/topics/, wiki/exercises/, wiki/entities/
and generates a structured index.md for LLM-assisted querying.
No API key required.
"""

import re
from pathlib import Path
from datetime import date

ROOT_DIR = Path(__file__).parent.parent
WIKI_DIR = ROOT_DIR / "wiki"
TOPICS_DIR = WIKI_DIR / "topics"
EXERCISES_DIR = WIKI_DIR / "exercises"
ENTITIES_DIR = WIKI_DIR / "entities"
INDEX_PATH = WIKI_DIR / "index.md"


def parse_frontmatter(filepath: Path) -> dict:
    """Extract YAML frontmatter fields from a markdown file."""
    text = filepath.read_text(encoding="utf-8", errors="ignore")
    meta = {}

    # Extract YAML block between --- delimiters
    match = re.match(r"^---\s*\n(.*?)\n---", text, re.DOTALL)
    if match:
        yaml_block = match.group(1)
        for line in yaml_block.splitlines():
            if ":" in line:
                key, _, value = line.partition(":")
                meta[key.strip()] = value.strip()

    # Extract first H1 heading as title
    h1 = re.search(r"^#\s+(.+)", text, re.MULTILINE)
    if h1:
        meta["title"] = h1.group(1).strip()
    else:
        meta["title"] = filepath.stem.replace("_", " ")

    # Extract first non-heading, non-frontmatter sentence as summary
    # Strip frontmatter first
    body = re.sub(r"^---.*?---\s*", "", text, flags=re.DOTALL)
    # Strip headings
    body = re.sub(r"^#+.+$", "", body, flags=re.MULTILINE)
    # Get first non-empty sentence
    sentences = [s.strip() for s in re.split(r"(?<=[.!?])\s+", body) if len(s.strip()) > 20]
    meta["summary"] = sentences[0][:120] if sentences else ""

    return meta


def format_entry(filepath: Path, meta: dict) -> str:
    """Format a single index entry line."""
    stem = filepath.stem
    title = meta.get("title", stem)
    summary = meta.get("summary", "")
    book_id = meta.get("book_id", meta.get("unit", "")).strip()
    tags_raw = meta.get("tags", "")

    # Clean up tags (remove brackets, quotes)
    tags = re.sub(r"[\[\]'\"]", "", tags_raw).strip()

    parts = [f"- [[{stem}]]"]
    if title and title != stem.replace("_", " "):
        parts[0] += f" — {title}"
    if summary:
        parts[0] += f". {summary}"
    if book_id:
        parts[0] += f" `{book_id}`"

    return parts[0]


def scan_category(directory: Path) -> list[tuple[Path, dict]]:
    """Scan a category directory and return sorted (path, meta) tuples."""
    results = []
    for f in sorted(directory.glob("*.md")):
        meta = parse_frontmatter(f)
        results.append((f, meta))
    return results


def build_index():
    print("[*] Scanning wiki nodes...")

    topics = scan_category(TOPICS_DIR)
    exercises = scan_category(EXERCISES_DIR)
    entities = scan_category(ENTITIES_DIR)

    today = date.today().isoformat()
    total = len(topics) + len(exercises) + len(entities)

    print(f"    Topics:    {len(topics)}")
    print(f"    Exercises: {len(exercises)}")
    print(f"    Entities:  {len(entities)}")
    print(f"    Total:     {total}")

    lines = []
    lines.append("---")
    lines.append("type: index")
    lines.append("title: Groove Hub Wiki Index")
    lines.append(f"last_updated: {today}")
    lines.append(f"total_nodes: {total}")
    lines.append("---")
    lines.append("")
    lines.append("# Groove Hub Wiki Index")
    lines.append("")
    lines.append("This file is auto-generated by `pipeline/build_index.py`.")
    lines.append("It serves as the primary navigation layer for LLM-assisted querying.")
    lines.append("When answering a question, read this file first to identify relevant nodes,")
    lines.append("then drill into the specific pages.")
    lines.append("")
    lines.append(f"> **Stats**: {len(topics)} Topics | {len(exercises)} Exercises | {len(entities)} Entities | **{total} Total Nodes**")
    lines.append(f"> Last updated: {today}")
    lines.append("")
    lines.append("---")
    lines.append("")

    # --- TOPICS ---
    lines.append(f"## Topics ({len(topics)} entries)")
    lines.append("")
    lines.append("Theory, technique, notation, and rhythm concepts.")
    lines.append("")

    # Group by first letter for readability
    current_letter = None
    for filepath, meta in topics:
        first_letter = filepath.stem[0].upper() if filepath.stem else "?"
        if first_letter != current_letter:
            current_letter = first_letter
            lines.append(f"### {current_letter}")
        lines.append(format_entry(filepath, meta))
    lines.append("")
    lines.append("---")
    lines.append("")

    # --- EXERCISES ---
    lines.append(f"## Exercises ({len(exercises)} entries)")
    lines.append("")
    lines.append("Drills, patterns, sticking exercises, and performance studies.")
    lines.append("")

    current_letter = None
    for filepath, meta in exercises:
        first_letter = filepath.stem[0].upper() if filepath.stem else "?"
        if first_letter != current_letter:
            current_letter = first_letter
            lines.append(f"### {current_letter}")
        lines.append(format_entry(filepath, meta))
    lines.append("")
    lines.append("---")
    lines.append("")

    # --- ENTITIES ---
    lines.append(f"## Entities ({len(entities)} entries)")
    lines.append("")
    lines.append("Instruments, authors, brands, notation symbols, and named concepts.")
    lines.append("")

    current_letter = None
    for filepath, meta in entities:
        first_letter = filepath.stem[0].upper() if filepath.stem else "?"
        if first_letter != current_letter:
            current_letter = first_letter
            lines.append(f"### {current_letter}")
        lines.append(format_entry(filepath, meta))
    lines.append("")
    lines.append("---")
    lines.append("")
    lines.append("*Generated by `pipeline/build_index.py` — re-run after adding new nodes.*")

    # Write output (Full)
    INDEX_PATH.write_text("\n".join(lines), encoding="utf-8")
    print(f"\n[V] index.md written to: {INDEX_PATH}")
    print(f"    Size: {INDEX_PATH.stat().st_size / 1024:.1f} KB")

    # --- SUMMARY INDEX ---
    summary_lines = []
    summary_lines.append("---")
    summary_lines.append("type: index_summary")
    summary_lines.append("title: Groove Hub Wiki Summary Index")
    summary_lines.append(f"last_updated: {today}")
    summary_lines.append(f"total_nodes: {total}")
    summary_lines.append("---")
    summary_lines.append("")
    summary_lines.append("# Wiki Summary Index")
    summary_lines.append("")
    summary_lines.append(f"> **Total Nodes**: {total} | Last updated: {today}")
    summary_lines.append("")
    
    def add_summary_section(title, nodes):
        summary_lines.append(f"## {title}")
        current_letter = None
        for filepath, _ in nodes:
            first_letter = filepath.stem[0].upper() if filepath.stem else "?"
            if first_letter != current_letter:
                current_letter = first_letter
                summary_lines.append(f"### {current_letter}")
            summary_lines.append(f"- [[{filepath.stem}]]")
        summary_lines.append("")

    add_summary_section("Topics", topics)
    add_summary_section("Exercises", exercises)
    add_summary_section("Entities", entities)

    SUMMARY_PATH = WIKI_DIR / "index_summary.md"
    SUMMARY_PATH.write_text("\n".join(summary_lines), encoding="utf-8")
    print(f"[V] index_summary.md written to: {SUMMARY_PATH}")
    print(f"    Size: {SUMMARY_PATH.stat().st_size / 1024:.1f} KB")


if __name__ == "__main__":
    build_index()
